front_left_foot_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - rev1
    - rev2
    - rev3
    - d_rev1
    - d_rev2
    - d_rev3
  gains:
    rev1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rev2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rev3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    d_rev1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    d_rev2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    d_rev3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
front_right_foot_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - rev4
    - rev5
    - rev6
    - d_rev4
    - d_rev5
    - d_rev6
  gains:
    rev4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rev5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rev6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    d_rev4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    d_rev5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    d_rev6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
middle_left_foot_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - rev7
    - rev8
    - rev9
    - d_rev7
    - d_rev8
    - d_rev9
  gains:
    rev7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rev8:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rev9:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    d_rev7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    d_rev8:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    d_rev9:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
middle_right_foot_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - rev10
    - rev11
    - rev12
    - d_rev10
    - d_rev11
    - d_rev12
  gains:
    rev10:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rev11:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rev12:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    d_rev10:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    d_rev11:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    d_rev12:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
end_left_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - rev13
    - rev14
    - rev15
    - d_rev13
    - d_rev14
    - d_rev15
  gains:
    rev13:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rev14:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rev15:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    d_rev13:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    d_rev14:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    d_rev15:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
end_right_foot_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - rev16
    - rev17
    - rev18
    - d_rev16
    - d_rev17
    - d_rev18
  gains:
    rev16:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rev17:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rev18:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    d_rev16:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    d_rev17:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    d_rev18:
      p: 100
      d: 1
      i: 1
      i_clamp: 1