controller_list:
  - name: front_left_foot_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - rev1
      - rev2
      - rev3
      - d_rev1
      - d_rev2
      - d_rev3
  - name: front_right_foot_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - rev4
      - rev5
      - rev6
      - d_rev4
      - d_rev5
      - d_rev6
  - name: middle_left_foot_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - rev7
      - rev8
      - rev9
      - d_rev7
      - d_rev8
      - d_rev9
  - name: middle_right_foot_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - rev10
      - rev11
      - rev12
      - d_rev10
      - d_rev11
      - d_rev12
  - name: end_left_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - rev13
      - rev14
      - rev15
      - d_rev13
      - d_rev14
      - d_rev15
  - name: end_right_foot_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - rev16
      - rev17
      - rev18
      - d_rev16
      - d_rev17
      - d_rev18